### ISSUE TITLE
Error al cargar glosario 

### ISSUE THREAD

**Issue by jmgarciamari** [civio/presupuesto-rubi#3]
Parece ser que es un problema de idioma, esta buscando el archivo glosario.csv y no existe, que debería cambiar para cargar los dos idiomas?

Gracias

**Comment by dcabo** [comment]
el repo de Rubí es un poco más complicado de manejar porque está pensado para mostrar varios idiomas. Si te vale con un idioma es más sencillo que mires el repositorio de Móstoles o Torrelodones, por ejemplo.

**Comment by jmgarciamari** [comment]
Disculpa, he creado un "issue" nuevo pensando que este estaba cerrado, necesito los dos idiomas, como podria hacerlo?, necesito dos bases de datos? me salta error al añadir la población que al ser la misma me dice un error de ID duplicada.

**Comment by dcabo** [comment]
no pasa nada, ya te he contestado en el otro issue. no puedo darte soporte de la parte multiidioma, está todavía muy verde
